#!/bin/bash

rm .shadow-cljs lib/cmds.js -Rf

sed -i 's/https.*gitlab.*lazuli/https:\/\/github.com\/mauricioszabo\/lazuli/' package.json
git checkout -b release-prepare-DELETE-THIS &&
npx shadow-cljs release dev &&
git rm -r src integration scripts &&
git add -f lib/cmds.js lib/main.js package.json &&
git commit -m 'Compiled version for release' &&
echo "Remember to tag your code now, and run push to github
