#!/bin/bash

rm -Rf integration/lazuli-tests/lib

if [ "$1" == "node" ]; then
    cd integration/lazuli-test && npm install && nohup npx shadow-cljs watch dev &
else
    docker run -d \
        --rm \
        --name=test-server \
        --network=host \
        -it \
        -u root \
        -v`pwd`:/work \
        atom \
        sh -c 'cd /work/integration/lazuli-tests && npm install && npx shadow-cljs watch tests'
fi
