#!/bin/bash

rm integration/lazuli-tests/lib/main.js
cd /work/integration/lazuli-tests && npm install && npx shadow-cljs watch tests &

for n in {1..35}; do
  ls integration/lazuli-tests/lib/main.js &>/dev/null && break
  echo "Test plug-in not compiled yet, waiting... ($n)"
  sleep 15
done

ls integration/lazuli-tests/lib/main.js &>/dev/null || (docker logs test-server && exit 1)
node integration/lazuli-tests/lib/main.js &
sh -c 'sleep 240 && killall atom' &

nohup ffmpeg -video_size 1024x768 -f x11grab -i :80.0 /tmp/junit/out.mpg &

cd integration/lazuli-tests

sleep 20
echo "--- RUNNING INTEGRATION TESTS ---"
echo -e "(load-file \"test/lazuli/tests.clj\")(in-ns 'lazuli.tests)(run-all-tests)\n" | nc localhost 3333 &
# npx shadow-cljs clj-eval "(load-file \"test/lazuli/tests.clj\")(in-ns 'lazuli.tests)(run-all-tests)" &

echo "--- AWAITING RESULTS ---"
fg %1
# echo -e "(System/exit 0)\n" | nc localhost 3333
# exit $result
