#!/bin/bash

mkdir /tmp/atom-ci/packages -p
ln -s `pwd` /tmp/atom-ci/packages
mkdir /tmp/clj_fixture -p

set -euo pipefail

export ATOM_HOME=/tmp/atom-ci
cd /tmp/clj_fixture
npm i shadow-cljs ws
npx shadow-cljs node-repl &
node lib/tests.js
